{% set name = "paprika" %}
{% set version = "1.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  url: https://github.com/GilsonLabUCSD/pAPRika/archive/v{{ version }}.tar.gz
  sha256: 0dc4fd3ddd9c9e8a39dba692c7d7df86be3243fcc8462b71f070bb6960946f1b


build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv


requirements:
  host:
    - python >=3.6
    - setuptools
    - pip

  run:
    - python >=3.6
    - numpy
    - scipy
    - setuptools
    - pymbar >=3.0.5
    - mdtraj
    - ambertools >=20.0

test:
  requires:
    - pytest
  imports:
    - paprika

about:
  home: https://github.com/GilsonLabUCSD/pAPRika
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: pAPRika is a toolkit for setting up, running, and analyzing free energy molecular dynamics simulations.
  doc_url: https://paprika.readthedocs.io/en/latest/
  dev_url: https://github.com/GilsonLabUCSD/pAPRika

extra:
  recipe-maintainers:
    - slochower
    - nhenriksen
    - jeff231li
