{% set name = "paprika" %}
{% set version = "1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  url: https://github.com/slochower/pAPRika/archive/v{{ version }}.tar.gz
  sha256: 14e680bdee5d917428482caff6c6b4a5d5b8e415f5ac80778c6779c926c7f2bd

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"


requirements:
  host:
    - python >=3.6
    - setuptools
    - pip

  run:
    - python >=3.6
    - numpy
    - scipy
    - setuptools
    - pymbar >=3.0.4
    - mdtraj
    - ambertools

test:
  requires:
    - pytest
  imports:
    - paprika

about:
  home: https://github.com/slochower/pAPRika
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: pAPRika is a toolkit for setting up, running, and analyzing free energy molecular dynamics simulations.
  doc_url: https://paprika.readthedocs.io/en/latest/
  dev_url: https://github.com/slochower/pAPRika

extra:
  recipe-maintainers:
    - slochower
    - nhenriksen
