{% set name = "paprika" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}


source:
  url: https://github.com/slochower/pAPRika/archive/v{{ version }}.tar.gz
  sha256: b423e994467b3004104e437389addb17d7e9b72553d130abff7e0bbf11bdc3aa 

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"


requirements:
  host:
    - python
    - setuptools
    - pip

  run:
    - python
    - numpy
    - scipy
    - setuptools
    - pymbar
    - mdtraj

test:
  requires:
    - pytest
  imports:
    - paprika

about:
  home: https://github.com/slochower/pAPRika
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: pAPRika is a toolkit for setting up, running, and analyzing free energy molecular dynamics simulations.
  doc_url: https://paprika.readthedocs.io/en/latest/
  dev_url: https://github.com/slochower/pAPRika

extra:
  recipe-maintainers:
    - slochower
    - nhenriksen
